### ISSUE TITLE
MSConvert_demultiplex error

### ISSUE THREAD

**Issue by jiyoungyoun** [ProteoWizard/pwiz#1877]
Hi ProteoWizard team,

I am using MSConvert to demultiplex DIA file acquired using 8m/z staggered window on Orbitrap 480 Exploris. I used 8 m/z staggered window setting recommended in Pino L et al., MCP 2020, following supplementary note 1 in this article. 

I used two filters in this order: 1) peak picking, then 2) demultiplex (10ppm error). See attached image.

I receive this error below:

D:\Raw_Files\DIA_test_K562_lysate\K562_100ng_DIA_8mz_staggered_test_20211125.raw
------------------------------
Starting...
Opening file "D:\Raw_Files\DIA_test_K562_lysate\K562_100ng_DIA_8mz_staggered_test_20211125.raw" for read...
Calculating SHA1 checksum...
Processing...
Writing "D:\Raw_Files\DIA_test_K562_lysate\K562_100ng_DIA_8mz_staggered_test_20211125.mzML"...
Failed - System.Exception: SpectrumToIndices() Number of demultiplexing windows changed. Minimum window size or window boundary tolerance may be set too low.
   at pwiz.CLI.msdata.MSDataFile.write(MSData msd, String filename, WriteConfig config, IterationListenerRegistry iterationListenerRegistry
   at MSConvertGUI.MainLogic.processFile(String filename, Config config, ReaderList readers, Map`2 usedOutputFilenames)
   at MSConvertGUI.MainLogic.Go(Config config, Map`2 usedOutputFilenames)
<img width="666" alt="MSConvert_Demultiplex setting" src="https://user-images.githubusercontent.com/45950915/144887236-2c0ee6fe-d534-4f88-8bc2-b1169c315753.PNG">

**Comment by chambm** [comment]
Try the latest version and the Show command-line option, then move to running on the command-line and try adding minWindowSize=1 to the demultiplex filter.
