### ISSUE TITLE
Peak Picking with CWT algorithm does not work in 64 bit version

### ISSUE THREAD

**Issue by kpnovoselov** [ProteoWizard/pwiz#721]
Hello,

When I try to convert Thermo raw file with profile spectra to mzML format with Peak Picking option selected, I got the following error message:

```
Calculating SHA1 checksum...
Processing...
Writing <filename>
Failed - System.Exception: [pwiz::CLI::msdata::MSDataFile::write] Unhandled exception: managed and native storage have different sizes
   at pwiz.CLI.msdata.MSDataFile.write(MSData msd, String filename, WriteConfig config, IterationListenerRegistry iterationListenerRegistry)
   at MSConvertGUI.MainLogic.processFile(String filename, Config config, ReaderList readers, Map`2 usedOutputFilenames)
   at MSConvertGUI.MainLogic.Go(Config config, Map`2 usedOutputFilenames)
```

Error message appears only in 64 bit version of the MSConvertGUI.exe and msconvert.exe. Everything works fine in 32 bit version.

**Comment by chambm** [comment]
Fixed in #744
